server:
  port: ${GATEWAY_PORT:8080} # API Gateway 监听的端口

spring:
  application:
    name: vibes-api-gateway # 应用名称
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # 用户服务路由 (UserService)
        - id: user_service_route
          uri: http://localhost:${USER_SERVICE_PORT:9081} # 用户服务端口由 .env 管理
          predicates:
            - Path=/v1/users/**

        # 帖子服务路由 (PostService)
        - id: post_service_route
          uri: http://localhost:${POST_SERVICE_PORT:9082} # 帖子服务端口由 .env 管理
          predicates:
            - Path=/v1/posts/**

        # 互动服务路由 (InteractionService)
        - id: interaction_service_route
          uri: http://localhost:${INTERACTION_SERVICE_PORT:9083} # 互动服务端口由 .env 管理
          predicates:
            - Path=/v1/interactions/**
          filters:
            - StripPrefix=1

        # 匹配服务路由 (MatchService)
        - id: match_service_route
          uri: http://localhost:${MATCH_SERVICE_PORT:9084} # 匹配服务端口由 .env 管理
          predicates:
            - Path=/v1/matches/**
          filters:
            - StripPrefix=1

        # 聊天服务路由 (ChatService)
        - id: chat_service_route
          uri: http://localhost:${CHAT_SERVICE_PORT:9085} # 聊天服务端口由 .env 管理
          predicates:
            - Path=/v1/chats/**
          filters:
            - StripPrefix=1

        # 区域热门内容服务路由 (RegionalHotContentService)
        - id: regional_hot_content_service_route
          uri: http://localhost:${REGIONAL_CONTENT_SERVICE_PORT:9086} # 区域热门内容服务端口由 .env 管理
          predicates:
            - Path=/v1/content/regional/**
          filters:
            - StripPrefix=1

        # 推荐流服务路由 (FeedService)
        - id: feed_service_route
          uri: http://localhost:${FEED_SERVICE_PORT:9087} # 推荐流服务端口由 .env 管理
          predicates:
            - Path=/v1/feed/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: false # MVP 阶段，我们使用硬编码URL，不依赖服务发现客户端 (如 Eureka/Consul)
          lower-case-service-id: true 

# Logging configuration to include Trace ID and Span ID
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

# Optional: Management endpoints (actuator) - good for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus # Expose common actuator endpoints
  endpoint:
    health:
      show-details: always # Show full health details 

# JWT Settings
vibes:
  jwt:
    # This secret key MUST BE a perfect match with the one in user-service.
    secret: ThisIsAReallyLongAndVerySecureSecretKeyForVibesAppOnlyDoNotShareIt 

# This setting is for Spring Cloud Gateway to discover services from Eureka, Consul, etc.
# If you are running services locally without a discovery server, use direct URLs like http://localhost:8081
# 'lb://' scheme stands for 'load balancer' and is used with service discovery.
main:
  web-application-type: reactive 